#!/sbin/openrc-run
# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="3d-Printer firmware, which combines the power of a general purpose computer with one or more micro-controllers"
name="klipper-mcu"

command=/usr/sbin/klipper-mcu
command_args="${klipper_mcu_args}"

supervisor="supervise-daemon"
pidfile="/run/klipper-mcu.pid"


depend() {
	use net	
}


